---
title: "homework6"
output: html_document
date: "2022-11-28"
---

## Problem 2

```{r}
library(tidyverse) 
library(dplyr)

homicide_df =
  read_csv("Data/homicide-data.csv") %>%
  janitor::clean_names() %>% 
  mutate(city = str_c(city,", ")) %>% 
  mutate(city_state = paste0(city, state)) %>% 
  filter(city_state != "Dallas, TX" & city_state != "Phoenix, AZ" & city_state != "Kansas City, MO" & city_state != "Tulsa, AL") %>%  
 filter(victim_race == "White" | victim_race == "Black") %>% 
 mutate(victim_age = as.numeric(victim_age))
  
```

```{r}
baltimore_df = 
  homicide_df %>% 
  filter(city_state == "Baltimore, MD") %>% 
  mutate(resolved = as.numeric(disposition == "Closed by arrest")) %>% 
  select(resolved, victim_age, victim_race, victim_sex)
  
baltimore_fit_logistic = 
  baltimore_df %>% 
  glm(resolved ~ victim_age + victim_race + victim_sex, data = ., family = binomial()) 

baltimore_fit_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate), Upper_CI = exp(estimate + 1.96*std.error), Lower_CI = exp(estimate - 1.96*std.error)) %>% 
  select(term, log_OR = estimate, OR, p.value, Lower_CI, Upper_CI) %>% 
  filter(term == "victim_sexMale") %>% 
  knitr::kable(digits = 3)
```

```{r}
allcity_df = 
  homicide_df %>% 
  mutate(resolved = as.numeric(disposition == "Closed by arrest")) %>% 
  select(city_state, resolved, victim_age, victim_race, victim_sex) 

model_results_df = 
allcity_df %>% 
  nest(citynest = resolved:victim_sex) %>% 
   mutate(allcity_fit_logistic_1 = map(citynest, ~glm(resolved ~ victim_age + victim_race + victim_sex, data = ., family = binomial())), allcity_fit_logistic = map(allcity_fit_logistic_1, broom::tidy)) %>% 
  select(city_state, allcity_fit_logistic) %>% 
  unnest(cols=allcity_fit_logistic) %>% 
  mutate(OR = exp(estimate), Upper_CI = exp(estimate + 1.96*std.error), Lower_CI = exp(estimate - 1.96*std.error)) %>% 
  select(city_state, term, log_OR = estimate, OR, p.value, Lower_CI, Upper_CI) %>% 
  filter(term == "victim_sexMale")  
  
model_results_df %>% 
  knitr::kable(digits = 3)

library(ggridges)
model_results_df %>% 
  #factor reorder
ggplot(aes(x = fct_reorder(city_state, OR), y = OR)) + 
  geom_point() + geom_errorbar(aes(ymin = Lower_CI, ymax = Upper_CI), width=.2,
                 position=position_dodge(.9)) + labs(
    title = "Odds of having a closed case by city",
    x = "City",
    y = "Odds Ratio"
  ) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


#Problem 3

```{r}

```

